name: Build and Deploy to VM via SSH

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up SSH agent
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Build Docker images locally (optional)
        run: |
          docker build -t smartretail-backend ./backend
          docker build -t smartretail-supplier-api ./supplier-api
      - name: Debug SSH and env variables
        env:
          VM_USER: ${{ secrets.VM_USER }}
          VM_HOST: ${{ secrets.VM_HOST }}
        run: |
          echo "VM_USER=$VM_USER"
          echo "VM_HOST=$VM_HOST"
          ssh -o StrictHostKeyChecking=no $VM_USER@$VM_HOST "hostname && whoami"

      - name: Copy files to VM
        env:
          VM_USER: ${{ secrets.VM_USER }}
          VM_HOST: ${{ secrets.VM_HOST }}
          RSYNC_RSH: "ssh -p 22"
        run: |
          rsync -avz --exclude='.git' --exclude='venv' --exclude='__pycache__' ./ $VM_USER@$VM_HOST:/home/$VM_USER/csp451-final/

      - name: Deploy Docker containers on VM
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/${{ secrets.VM_USER }}/csp451-final
            docker-compose down
            docker-compose up -d --build
